swagger: 2.0
info:
  version: 1.0
  title: blah
  description: 'TODO: Add Description'
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: example.com
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /get:
    get:
      description: 'TODO: Add Description'
      tags:
      - Misc
      operationId: httpbin.org/get
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: 
      security: []
      x-unitTests:
      - request:
          method: GET
          uri: /get
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: httpbin.org/get
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /environments:
    get:
      description: 'TODO: Add Description'
      tags:
      - Misc
      operationId: GET Environment
      produces:
      - application/json
      parameters:
      - name: X-Api-Key
        in: header
        required: true
        type: string
      responses:
        200:
          description: 
      security: []
      x-unitTests:
      - request:
          method: GET
          uri: /environments
          headers:
            X-Api-Key: '{{postman_api_key}}'
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: GET Environment
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /environments/{environment_uid}:
    get:
      description: 'TODO: Add Description'
      tags:
      - Misc
      operationId: GET Single Environment
      produces:
      - application/json
      parameters:
      - name: apikey
        in: query
        required: true
        type: string
      - name: environment_uid
        in: path
        required: true
        type: string
      responses:
        200:
          description: 
      security: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /collections/{collection_uid}:
    get:
      description: 'TODO: Add Description'
      tags:
      - Misc
      operationId: GET Single Collection
      produces:
      - application/json
      parameters:
      - name: apikey
        in: query
        required: true
        type: string
      - name: collection_uid
        in: path
        required: true
        type: string
      responses:
        200:
          description: 
      security: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /collections:
    get:
      description: 'TODO: Add Description'
      tags:
      - Misc
      operationId: GET Collections
      produces:
      - application/json
      parameters:
      - name: apikey
        in: query
        required: true
        type: string
      responses:
        200:
          description: 
      security: []
      x-unitTests:
      - request:
          method: GET
          uri: /collections?apikey={{api_key}}
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: GET Collections
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
